

trigger:
    branches:
      include:
        - public
        
variables:
    packageName: 'eclypses-aws-mte-relay-client-ios'
    relayDirectory: '$(Build.Repository.LocalPath)'


pool: 'MacOS - Intel'

steps:

- task: InstallSSHKey@0
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/public')
  displayName: 'Install the SSH key'
  inputs:
    knownHostsEntry: '$(known_hosts_entry)'
    sshPublicKey: '$(ado_pk)'
    sshKeySecureFile: 'id_ed25519'

  #  Not building at the moment but I'll want to correct this later JGW
# - script: |
#     xcodebuild -scheme MteRelay -destination 'platform=iOS Simulator,OS=16.2,name=iPhone 15 Pro' build
#   displayName: 'Build on MteRelay Package'
#   workingDirectory: $(relayDirectory)

- task: DeleteFiles@1
  displayName: 'Delete unnecessary files before push to public remote'
  condition: and(
               succeeded(),
               eq(variables['Build.SourceBranch'], 'refs/heads/public')
             )
  inputs:
    SourceFolder: $(relayDirectory)
    Contents: |
      .gitignore
      **/*.yml
      UPDATEME.md

- script: |
    git add .
    git commit -am 'Commit unnecessary file deletion'
  displayName: 'Commit unnecessary file deletion'
  condition: and(
               succeeded(),
               eq(variables['Build.SourceBranch'], 'refs/heads/public')
             )
  workingDirectory: $(relayDirectory)

- task: CmdLine@2
  displayName: 'Push to Public GitHub'
  condition: and(
               succeeded(),
               eq(variables['Build.SourceBranch'], 'refs/heads/public')
             )
  inputs:
    script: |
      ssh-keyscan -t ed25519 github.com >> ~/.ssh/known_hosts
      git push git@github.com:Eclypses/$(Build.Repository.Name).git HEAD:refs/heads/public --force  --tags
    workingDirectory: $(relayDirectory)

